artifact_location: /content/wildfire-smoke-detection/runs/mlflow/906565123661874039
creation_time: 1778340197405
experiment_id: '906565123661874039'
last_update_time: 1778340197405
lifecycle_stage: active
name: /Shared/Ultralytics
trace_location: null
workspace: default
